[server]
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[logger]
level = "error"
messageFormat = "%(asctime)s - %(message)s"
maxBytes = 1024  # Maximum size of each log file in bytes
backupCount = 1  # Number of backup log files to keep 