[deploy]
# Explicitly specify which requirements files to use
requirements_files = ["requirements.txt"]
# Ignore other requirements files
ignore_requirements_files = ["root_requirements.txt", "ml_dev_requirements.txt", "cpp_requirements.txt"] 